### ISSUE TITLE
Add workshops

### ISSUE THREAD

**Issue by merelinguist** [Prog-Soc/ProgSoc-Website#22]
### Possible workshops

- [ ] Personal Website
- [ ] That was easy
- [ ] Geometric pattern
- [ ] Dodge
- [ ] Platformer
- [ ] Collaborative sketch
- [ ] Dashboard
- [ ] Rails notes

**Comment by Gunner237** [comment]
I'll leave that to you!
Also a template projects page (check emails), or space on the homepage for links to featured projects might be good (I defer to your design skills)

**Comment by merelinguist** [comment]
What do you mean by "template projects page"?

**Comment by Gunner237** [comment]
I.e. a page where we can show off various projects (with space for sample code, link to full code, screenshot of app/site/whatever working if applicable)...

**Comment by merelinguist** [comment]
:+1: Okay
