### ISSUE TITLE
Calendar displays next meeting as the following Thursday, even during holidays.

### ISSUE THREAD

**Issue by Gunner237** [Prog-Soc/ProgSoc-Website#29]
Somewhat of a blue sky point, but the calendar will always display the next thursday as the next meeting - even during holidays. Might be as simple(!) as pushing an update at the beginning/end of each term that replaces the calendar with a holiday message... or an array of term dates? To discuss...

**Comment by merelinguist** [comment]
Hmmmm, I can think of a couple of solutions.

The most performant solution would be to push to the repo before every meeting, and simply display the date statically, but of course that would be pretty impractical. 

I can throw together a quick holiday message for now, but I have an idea for the long-term, shoot me a message on Slack to discuss

**Comment by merelinguist** [comment]
Will be fixed in next version, see #30
